import Head from "next/head";
import Sidebar from "@/components/Sidebar/index";
import MainSection from "@/components/MainSection";
import { Provider } from "react-redux";
import {store} from "@/redux/tasks/store/store";

export default function Home() {
  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Sidebar />
        <MainSection />
      </main>
    </Provider>
  );
}
